export const LIVE_CHAIN_IDS = process.env.LIVE_CHAIN_IDS.split(',');
export const RPC_CHAIN_IDS = process.env.RPC_CHAIN_IDS.split(',');

export const ARBITRUM_RPC = 'https://lb.drpc.org/ogrpc?network=arbitrum&dkey=AvM7kbbCQE_wtg3gyulIGctkFcJh9VsR7pPangOF84-p';
export const ETH_MAINNET_RPC = 'https://lb.drpc.org/ogrpc?network=ethereum&dkey=AvM7kbbCQE_wtg3gyulIGctkFcJh9VsR7pPangOF84-p';
export const SEPOLIA_RPC = 'https://lb.drpc.org/ogrpc?network=sepolia&dkey=AvM7kbbCQE_wtg3gyulIGctkFcJh9VsR7pPangOF84-p';
export const MANTLE_RPC = 'https://lb.drpc.org/ogrpc?network=mantle&dkey=AvM7kbbCQE_wtg3gyulIGctkFcJh9VsR7pPangOF84-p';
export const MANTLE_SEPOLIA_RPC = 'https://lb.drpc.org/ogrpc?network=mantle-sepolia&dkey=AvM7kbbCQE_wtg3gyulIGctkFcJh9VsR7pPangOF84-p';

export const MICHI_HELPER_ADDRESS_ARBITRUM = '0x9ee8acd1fc91d3c71be4cc1065c32653afc4b43c';
export const MICHI_HELPER_ADDRESS_SEPOLIA = MICHI_HELPER_ADDRESS_ARBITRUM;
export const MICHI_HELPER_ADDRESS_ETH_MAINNET = MICHI_HELPER_ADDRESS_ARBITRUM;
export const MICHI_HELPER_ADDRESS_MANTLE = MICHI_HELPER_ADDRESS_ARBITRUM;
export const MICHI_HELPER_ADDRESS_MANTLE_SEPOLIA = MICHI_HELPER_ADDRESS_ARBITRUM;

export const MICHI_STAKING_ADDRESS_ARBITRUM = '0xaa4a7ddEc19e41098faf324BD333fE9704176377';
export const MICHI_STAKING_ADDRESS_SEPOLIA = '';
export const MICHI_STAKING_ADDRESS_ETH_MAINNET = '';
export const MICHI_STAKING_ADDRESS_MANTLE = '';
export const MICHI_STAKING_ADDRESS_MANTLE_SEPOLIA = '';


export const MICHI_WALLET_NFT_ADDRESS_ARBITRUM = '0xd022977a22f9a681df8f3c51ed9ad144bdc5bb38';
export const MICHI_WALLET_NFT_ADDRESS_SEPOLIA = MICHI_WALLET_NFT_ADDRESS_ARBITRUM;
export const MICHI_WALLET_NFT_ADDRESS_ETH_MAINNET = MICHI_WALLET_NFT_ADDRESS_ARBITRUM;
export const MICHI_WALLET_NFT_ADDRESS_MANTLE = MICHI_WALLET_NFT_ADDRESS_ARBITRUM;
export const MICHI_WALLET_NFT_ADDRESS_MANTLE_SEPOLIA = MICHI_WALLET_NFT_ADDRESS_ARBITRUM;

export const MASTER_CHEF_ADDRESS_SEPOLIA = '0xaf8a5c116b61f0272c88f3ac4c327f580c67a43a';
export const MASTER_CHEF_ADDRESS_MANTLE = '0x27a05d9ce13618665a9d3bbef5cdffcd19ed688b';

export const MOCK_MOE_PAIR_ADDRESS_SEPOLIA = '0xae26658624368391935a62eb50bb954b1ae180f2';
export const MOCK_MOE_PAIR_ADDRESS_MANTLE = '0xf44a81156475f2dfbb371b0171228aa40c9e2dcf';

export const TOKEN_PAIR_SYMBOLS_SEPOLIA = ['METH/PCH'];
export const TOKEN_PAIR_SYMBOLS_MANTLE = ['PCH/METH'];

export const MICHI_MARKETPLACE_ADDRESS_ARBITRUM = '0xfe8e4a6dbab35359c70781aa6279c0082ecef4f7';
export const MICHI_MARKETPLACE_ADDRESS_SEPOLIA = MICHI_MARKETPLACE_ADDRESS_ARBITRUM;
export const MICHI_MARKETPLACE_ADDRESS_ETH_MAINNET = MICHI_MARKETPLACE_ADDRESS_ARBITRUM;

export const BATCH_CALLER_ADDRESS_ARBITRUM = '0xba9424C141CE5ccE6559B0473e670c45227FA906';
export const BATCH_CALLER_ADDRESS_SEPOLIA = '0x92dEC1b6C54203098Cc4d854619f63C231043Ae3';
export const BATCH_CALLER_ADDRESS_ETH_MAINNET = '0x64A8bfE83b7F5cB97B9f4B0837f94Eb18113c50D';
export const BATCH_CALLER_ADDRESS_MANTLE = '0x46D31cdcC0b14407F7b3C03486b6C916F337c48f';
export const BATCH_CALLER_ADDRESS_MANTLE_SEPOLIA = '0x548F4C50A3c8802fD5DC6a22212dA86423AaB2c4';

export const ARBITRUM_CHAIN_ID = '0xa4b1';
export const ETH_MAINNET_CHAIN_ID = '0x1';
export const SEPOLIA_CHAIN_ID = '0xaa36a7';
export const MANTLE_CHAIN_ID = '0x1388';
export const MANTLE_SEPOLIA_CHAIN_ID = '0x138b';

export const WALLET_CREATED_TOPIC = 'WalletCreated(address,address,address,uint256)';
export const DEPOSIT_TOPIC = 'Deposit(address,address,address,uint256,uint256)';
export const WALLET_PURCHASED_TOPIC = 'WalletPurchased(address,address,address,address,uint256,uint256,uint256)';
export const ORDERS_CANCELLED_TOPIC = 'OrdersCancelled(address,uint256[])';
export const ALL_ORDERS_CANCELLED_TOPIC = 'AllOrdersCancelled(address,uint256)';

export const CHAIN_NAMES = {
    [ARBITRUM_CHAIN_ID]: 'Arbitrum',
    [ETH_MAINNET_CHAIN_ID]: 'Eth',
    [SEPOLIA_CHAIN_ID]: 'Sepolia',
    [MANTLE_CHAIN_ID]: 'Mantle',
    [MANTLE_SEPOLIA_CHAIN_ID]: 'MantleSepolia',
};

export const SCANNER_BASE_TX_URLS = {
    [ARBITRUM_CHAIN_ID]: 'https://arbiscan.io/tx',
    [ETH_MAINNET_CHAIN_ID]: 'https://etherscan.io/tx',
    [SEPOLIA_CHAIN_ID]: 'https://sepolia.etherscan.io/tx',
    [MANTLE_CHAIN_ID]: 'https://explorer.mantle.xyz/',
    [MANTLE_SEPOLIA_CHAIN_ID]: 'https://explorer.sepolia.mantle.xyz/',
};


export const MICHI_WALLET_NFTS_ADDRESSES = {
    [ARBITRUM_CHAIN_ID]: MICHI_WALLET_NFT_ADDRESS_ARBITRUM,
    [ETH_MAINNET_CHAIN_ID]: MICHI_WALLET_NFT_ADDRESS_ETH_MAINNET,
    [SEPOLIA_CHAIN_ID]: MICHI_WALLET_NFT_ADDRESS_SEPOLIA,
    [MANTLE_CHAIN_ID]: MICHI_WALLET_NFT_ADDRESS_MANTLE,
    [MANTLE_SEPOLIA_CHAIN_ID]: MICHI_WALLET_NFT_ADDRESS_MANTLE_SEPOLIA,
};

export const MASTER_CHEF_ADDRESSES = {
    [SEPOLIA_CHAIN_ID]: MASTER_CHEF_ADDRESS_SEPOLIA,
    [MANTLE_CHAIN_ID]: MASTER_CHEF_ADDRESS_MANTLE,
};

export const MOCK_MOE_PAIR_ADDRESSES = {
    [SEPOLIA_CHAIN_ID]: MOCK_MOE_PAIR_ADDRESS_SEPOLIA,
    [MANTLE_CHAIN_ID]:  MOCK_MOE_PAIR_ADDRESS_MANTLE,
};

export const TOKEN_PAIRS = {
    [SEPOLIA_CHAIN_ID]: TOKEN_PAIR_SYMBOLS_SEPOLIA,
    [MANTLE_CHAIN_ID]:  TOKEN_PAIR_SYMBOLS_MANTLE,
};

export const MICHI_HELPER_ADDRESSES = {
    [ARBITRUM_CHAIN_ID]: MICHI_HELPER_ADDRESS_ARBITRUM,
    [ETH_MAINNET_CHAIN_ID]: MICHI_HELPER_ADDRESS_ETH_MAINNET,
    [SEPOLIA_CHAIN_ID]: MICHI_HELPER_ADDRESS_SEPOLIA,
    [MANTLE_CHAIN_ID]: MICHI_HELPER_ADDRESS_MANTLE,
    [MANTLE_SEPOLIA_CHAIN_ID]: MICHI_HELPER_ADDRESS_MANTLE_SEPOLIA,
};

export const MICHI_STAKING_ADDRESSES = {
    [ARBITRUM_CHAIN_ID]: MICHI_STAKING_ADDRESS_ARBITRUM,
    [ETH_MAINNET_CHAIN_ID]: MICHI_STAKING_ADDRESS_ETH_MAINNET,
    [SEPOLIA_CHAIN_ID]: MICHI_STAKING_ADDRESS_SEPOLIA,
    [MANTLE_CHAIN_ID]: MICHI_STAKING_ADDRESS_MANTLE,
    [MANTLE_SEPOLIA_CHAIN_ID]: MICHI_STAKING_ADDRESS_MANTLE_SEPOLIA,
};

export const MICHI_MARKETPLACE_ADDRESSES = {
    [ARBITRUM_CHAIN_ID]: MICHI_MARKETPLACE_ADDRESS_ARBITRUM,
    [ETH_MAINNET_CHAIN_ID]: MICHI_MARKETPLACE_ADDRESS_ETH_MAINNET,
    [SEPOLIA_CHAIN_ID]: MICHI_MARKETPLACE_ADDRESS_SEPOLIA,
};

export const BATCH_CALLER_ADDRESSES = {
    [ARBITRUM_CHAIN_ID]: BATCH_CALLER_ADDRESS_ARBITRUM,
    [ETH_MAINNET_CHAIN_ID]: BATCH_CALLER_ADDRESS_ETH_MAINNET,
    [SEPOLIA_CHAIN_ID]: BATCH_CALLER_ADDRESS_SEPOLIA,
    [MANTLE_CHAIN_ID]: BATCH_CALLER_ADDRESS_MANTLE,
    [MANTLE_SEPOLIA_CHAIN_ID]: BATCH_CALLER_ADDRESS_MANTLE_SEPOLIA,
};


export const RPC_ENDPOINTS = {
    [ARBITRUM_CHAIN_ID]: ARBITRUM_RPC,
    [ETH_MAINNET_CHAIN_ID]: ETH_MAINNET_RPC,
    [SEPOLIA_CHAIN_ID]: SEPOLIA_RPC,
    [MANTLE_CHAIN_ID]: MANTLE_RPC,
    [MANTLE_SEPOLIA_CHAIN_ID]: MANTLE_SEPOLIA_RPC,
};

// When we started tracking points
export const MICHI_LAUNCH_DATES = {
    [ARBITRUM_CHAIN_ID]: new Date('2024-03-25T08:00:00Z'),
    [ETH_MAINNET_CHAIN_ID]: new Date('2024-04-05T08:00:00Z'),
    [SEPOLIA_CHAIN_ID]: new Date('2024-03-29T08:00:00Z'),
    [MANTLE_CHAIN_ID]: new Date('2024-08-25T00:00:00Z'),
    [MANTLE_SEPOLIA_CHAIN_ID]: new Date('2024-08-25T00:00:00Z')
};

// When the contracts were launched
export const MICHI_START_DATES = {
    [ARBITRUM_CHAIN_ID]: new Date('2024-03-23T17:11:40Z'),
    [ETH_MAINNET_CHAIN_ID]: new Date('2024-04-03T02:54:23Z'),
    [SEPOLIA_CHAIN_ID]: new Date('2024-03-28T16:41:48Z'),
    [MANTLE_CHAIN_ID]: new Date('2024-08-08T21:41:54Z'),
    [MANTLE_SEPOLIA_CHAIN_ID]: new Date('2024-08-07T01:47:57Z')
};

export const CHAIN_POINT_MULTIPLIER_CUTOFFS = {
    [ARBITRUM_CHAIN_ID]: [
        {
            endDate: new Date('2024-04-17T08:00:00Z'),
            multiplier: 3
        },
        {
            endDate: new Date('2024-04-24T08:00:00Z'),
            multiplier: 2
        },
    ],
    [ETH_MAINNET_CHAIN_ID]: [
        {
            endDate: new Date('2024-04-12T08:00:00Z'),
            multiplier: 3
        },
        {
            endDate: new Date('2024-04-19T08:00:00Z'),
            multiplier: 2
        },
    ],
    [SEPOLIA_CHAIN_ID]: [],
    [MANTLE_CHAIN_ID]: [],
    [MANTLE_SEPOLIA_CHAIN_ID]: []
};

export const TOKEN_EXCLUSION_LIST = {
    [ARBITRUM_CHAIN_ID]: [
        '0xf28db483773e3616da91fdfa7b5d4090ac40cc59', // YT-weETH-25APR2024
        '0x28df0f193d8e45073bc1db6f2347812c031ba818' // YT-rsETH-25APR2024 
    ],
    [ETH_MAINNET_CHAIN_ID]: [
        '0x20c8cf9714339fd018898cb5de84c089e48d1c87', // YT-sUSDE-25APR2024
        '0x256fb830945141f7927785c06b65dabc3744213c' // YT-ezETH-25APR2024
    ],
    [SEPOLIA_CHAIN_ID]: [],
    [MANTLE_CHAIN_ID]: [],
    [MANTLE_SEPOLIA_CHAIN_ID]: [],
};

export const EXTRA_WITHDRAWABLE_TOKENS = {
    [ARBITRUM_CHAIN_ID]: [
    ],
    [ETH_MAINNET_CHAIN_ID]: [
        '0xfe0c30065b384f05761f15d0cc899d4f9f9cc0eb', // etherfi
        '0x3b50805453023a91a8bf641e279401a0b23fa6f9' // renzo
    ],
    [SEPOLIA_CHAIN_ID]: [],
    [MANTLE_CHAIN_ID]: [],
    [MANTLE_SEPOLIA_CHAIN_ID]: []
};


export const RENZO_CLAIM_TOKEN_ADDRESS = '0x3b50805453023a91a8bf641e279401a0b23fa6f9';